
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rightCurlyB = 15;
  public static final int operatorZeroMore = 8;
  public static final int comment = 2;
  public static final int number = 24;
  public static final int multicomment = 3;
  public static final int arrow = 18;
  public static final int nextL = 20;
  public static final int separator = 11;
  public static final int conj = 26;
  public static final int singleQuoMark = 21;
  public static final int operatorOneMore = 9;
  public static final int semicolon = 16;
  public static final int EOF = 0;
  public static final int operatorZeroOne = 10;
  public static final int id = 5;
  public static final int virgulilla = 13;
  public static final int error = 1;
  public static final int stringVal = 4;
  public static final int colon = 17;
  public static final int operatorOr = 7;
  public static final int operatorAnd = 6;
  public static final int asciiChar = 25;
  public static final int doubleQuoMark = 22;
  public static final int letter = 23;
  public static final int nextLine = 19;
  public static final int comma = 12;
  public static final int leftCurlyB = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comment",
  "multicomment",
  "stringVal",
  "id",
  "operatorAnd",
  "operatorOr",
  "operatorZeroMore",
  "operatorOneMore",
  "operatorZeroOne",
  "separator",
  "comma",
  "virgulilla",
  "leftCurlyB",
  "rightCurlyB",
  "semicolon",
  "colon",
  "arrow",
  "nextLine",
  "nextL",
  "singleQuoMark",
  "doubleQuoMark",
  "letter",
  "number",
  "asciiChar",
  "conj"
  };
}

