
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

import Main.EXREGAN;
import Objects.*;
import ui.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Syntactical extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Syntactical() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Syntactical(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Syntactical(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\035\000\002\002\004\000\002\002\004\000\002\003" +
    "\004\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\004\000\002\003\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\004\000\002\006\010\000\002" +
    "\010\005\000\002\010\005\000\002\010\003\000\002\010" +
    "\003\000\002\007\006\000\002\012\005\000\002\012\005" +
    "\000\002\012\004\000\002\012\004\000\002\012\004\000" +
    "\002\012\005\000\002\012\003\000\002\005\006\000\002" +
    "\011\005\000\002\011\003\000\002\013\005\000\002\013" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\020\004\001\002\000\020\003\020\004" +
    "\016\005\022\007\007\015\014\021\010\026\013\001\002" +
    "\000\004\002\006\001\002\000\004\002\001\001\002\000" +
    "\006\023\054\024\055\001\002\000\004\002\ufffa\001\002" +
    "\000\004\002\000\001\002\000\020\003\020\004\016\005" +
    "\022\007\007\015\014\021\010\026\013\001\002\000\004" +
    "\023\030\001\002\000\004\015\027\001\002\000\020\003" +
    "\ufff9\004\ufff9\005\ufff9\007\ufff9\015\ufff9\021\ufff9\026\ufff9" +
    "\001\002\000\020\003\020\004\016\005\022\007\007\015" +
    "\014\021\010\026\013\001\002\000\020\003\020\004\016" +
    "\005\022\007\007\015\014\021\010\026\013\001\002\000" +
    "\020\003\020\004\016\005\022\007\007\015\014\021\010" +
    "\026\013\001\002\000\020\003\ufff8\004\ufff8\005\ufff8\007" +
    "\ufff8\015\ufff8\021\ufff8\026\ufff8\001\002\000\020\003\020" +
    "\004\016\005\022\007\007\015\014\021\010\026\013\001" +
    "\002\000\004\002\ufffe\001\002\000\004\002\ufffb\001\002" +
    "\000\004\002\ufffc\001\002\000\004\002\uffff\001\002\000" +
    "\020\003\ufff7\004\ufff7\005\ufff7\007\ufff7\015\ufff7\021\ufff7" +
    "\026\ufff7\001\002\000\004\007\031\001\002\000\004\024" +
    "\032\001\002\000\006\007\036\025\035\001\002\000\004" +
    "\022\ufff2\001\002\000\004\022\052\001\002\000\010\016" +
    "\045\017\046\022\uffe5\001\002\000\010\016\040\017\041" +
    "\022\uffe7\001\002\000\004\022\ufff3\001\002\000\004\007" +
    "\044\001\002\000\004\007\042\001\002\000\004\022\ufff5" +
    "\001\002\000\004\022\uffe8\001\002\000\006\016\040\022" +
    "\uffe7\001\002\000\004\025\051\001\002\000\004\025\047" +
    "\001\002\000\004\022\ufff4\001\002\000\004\022\uffe6\001" +
    "\002\000\006\016\045\022\uffe5\001\002\000\020\003\ufff6" +
    "\004\ufff6\005\ufff6\007\ufff6\015\ufff6\021\ufff6\026\ufff6\001" +
    "\002\000\004\002\ufffd\001\002\000\004\006\100\001\002" +
    "\000\020\006\061\010\057\011\060\012\065\013\062\014" +
    "\064\020\063\001\002\000\004\022\077\001\002\000\020" +
    "\006\061\010\057\011\060\012\065\013\062\014\064\020" +
    "\063\001\002\000\020\006\061\010\057\011\060\012\065" +
    "\013\062\014\064\020\063\001\002\000\022\006\uffea\010" +
    "\uffea\011\uffea\012\uffea\013\uffea\014\uffea\020\uffea\022\uffea" +
    "\001\002\000\020\006\061\010\057\011\060\012\065\013" +
    "\062\014\064\020\063\001\002\000\004\007\070\001\002" +
    "\000\020\006\061\010\057\011\060\012\065\013\062\014" +
    "\064\020\063\001\002\000\020\006\061\010\057\011\060" +
    "\012\065\013\062\014\064\020\063\001\002\000\022\006" +
    "\uffee\010\uffee\011\uffee\012\uffee\013\uffee\014\uffee\020\uffee" +
    "\022\uffee\001\002\000\022\006\uffec\010\uffec\011\uffec\012" +
    "\uffec\013\uffec\014\uffec\020\uffec\022\uffec\001\002\000\004" +
    "\021\071\001\002\000\022\006\uffeb\010\uffeb\011\uffeb\012" +
    "\uffeb\013\uffeb\014\uffeb\020\uffeb\022\uffeb\001\002\000\022" +
    "\006\uffed\010\uffed\011\uffed\012\uffed\013\uffed\014\uffed\020" +
    "\uffed\022\uffed\001\002\000\020\006\061\010\057\011\060" +
    "\012\065\013\062\014\064\020\063\001\002\000\022\006" +
    "\uffef\010\uffef\011\uffef\012\uffef\013\uffef\014\uffef\020\uffef" +
    "\022\uffef\001\002\000\020\006\061\010\057\011\060\012" +
    "\065\013\062\014\064\020\063\001\002\000\022\006\ufff0" +
    "\010\ufff0\011\ufff0\012\ufff0\013\ufff0\014\ufff0\020\ufff0\022" +
    "\ufff0\001\002\000\020\003\ufff1\004\ufff1\005\ufff1\007\ufff1" +
    "\015\ufff1\021\ufff1\026\ufff1\001\002\000\004\022\101\001" +
    "\002\000\020\003\uffe9\004\uffe9\005\uffe9\007\uffe9\015\uffe9" +
    "\021\uffe9\026\uffe9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\002\004\001\001\000\014\003\010\004" +
    "\011\005\016\006\014\007\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\003\052\004\011\005\016\006\014" +
    "\007\020\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\003\025\004\011\005\016\006\014" +
    "\007\020\001\001\000\014\003\024\004\011\005\016\006" +
    "\014\007\020\001\001\000\014\003\023\004\011\005\016" +
    "\006\014\007\020\001\001\000\002\001\001\000\014\003" +
    "\022\004\011\005\016\006\014\007\020\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\010\033\011\036\013\032\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\042\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\012\055\001" +
    "\001\000\002\001\001\000\004\012\074\001\001\000\004" +
    "\012\072\001\001\000\002\001\001\000\004\012\071\001" +
    "\001\000\002\001\001\000\004\012\066\001\001\000\004" +
    "\012\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\073\001\001\000\002\001\001\000\004\012\075\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Syntactical$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Syntactical$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Syntactical$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    //metodos para controlar el arbol de expresiones
    public static int ids = 0;
    public static AST rootT;

    //metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);
        
        TError tmp = new TError("Sintactico",lexema,"Caracter no esperado",fila,columna);
        EXREGAN.errores.add(tmp);
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperación
    public  void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;

        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);
        
        TError tmp = new TError("Sintactico",lexema,"Caracter no esperado",fila,columna);
        EXREGAN.errores.add(tmp);
        
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Syntactical$actions {
  private final Syntactical parser;

  /** Constructor */
  CUP$Syntactical$actions(Syntactical parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Syntactical$do_action_part00000000(
    int                        CUP$Syntactical$act_num,
    java_cup.runtime.lr_parser CUP$Syntactical$parser,
    java.util.Stack            CUP$Syntactical$stack,
    int                        CUP$Syntactical$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Syntactical$result;

      /* select the action based on the action number */
      switch (CUP$Syntactical$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).value;
		RESULT = start_val;
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Syntactical$parser.done_parsing();
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= leftCurlyB PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMBODY ::= comment PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // PROGRAMBODY ::= multicomment PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // PROGRAMBODY ::= DEFINITION PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // PROGRAMBODY ::= EVALUATION PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // PROGRAMBODY ::= error PROGRAMBODY 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // PROGRAMBODY ::= rightCurlyB 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PROGRAMBODY",1, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DEFINITION ::= CONJUNTO 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("DEFINITION",2, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // DEFINITION ::= EXPRG 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("DEFINITION",2, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DEFINITION ::= separator separator 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("DEFINITION",2, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // CONJUNTO ::= conj colon id arrow NOTATION semicolon 
            {
              Object RESULT =null;
		 System.out.println("Nuevo conjunto"); 
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("CONJUNTO",4, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-5)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NOTATION ::= id virgulilla id 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("NOTATION",6, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NOTATION ::= asciiChar virgulilla asciiChar 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("NOTATION",6, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NOTATION ::= LISTVAL 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("NOTATION",6, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NOTATION ::= ASCIIS 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("NOTATION",6, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // EXPRG ::= id arrow PREFIXREGEX semicolon 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-3)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).value;
		 
            parser.ids++;
            AST finR = new AST(parser.ids, "#", null, null); 
            parser.ids++;
            AST newR = new AST(parser.ids, ".", (AST)r, finR);
            
            parser.rootT = newR;
            parser.rootT.generateAST((String) n);
            EXREGAN.trees.add((AST)r);
            EXREGAN.menu.addTree((String)n, EXREGAN.menu.getTrees());
            System.out.println("Nueva expresión regular"); 
          
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("EXPRG",5, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-3)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // PREFIXREGEX ::= operatorAnd PREFIXREGEX PREFIXREGEX 
            {
              Object RESULT =null;
		int rileft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).left;
		int riright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).right;
		Object ri = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).value;
		int leleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		
                    System.out.println("nuevo . P");
                    parser.ids++;
                    RESULT = new AST(parser.ids, ".", (AST)le, (AST)ri); 
                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // PREFIXREGEX ::= operatorOr PREFIXREGEX PREFIXREGEX 
            {
              Object RESULT =null;
		int rileft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).left;
		int riright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).right;
		Object ri = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).value;
		int leleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		
                    System.out.println("nuevo | P");
                    parser.ids++;
                    RESULT = new AST(parser.ids, "|", (AST)le, (AST)ri); 
 
                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // PREFIXREGEX ::= operatorZeroMore PREFIXREGEX 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		
                    System.out.println("nuevo * P");
                    parser.ids++;
                    RESULT = new AST(parser.ids, "*", (AST)le, null); 

                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // PREFIXREGEX ::= operatorOneMore PREFIXREGEX 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		
                    System.out.println("nuevo + P");
                    parser.ids++;
                    RESULT = new AST(parser.ids, "+", (AST)le, null); 

                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // PREFIXREGEX ::= operatorZeroOne PREFIXREGEX 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		
                    System.out.println("nuevo ? P");
                    parser.ids++;
                    RESULT = new AST(parser.ids, "?", (AST)le, null); 
 
                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // PREFIXREGEX ::= leftCurlyB id rightCurlyB 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-1)).value;
		
                    System.out.println("nuevo id"); 
                    AST newVal = new AST(parser.ids, o, null, null );
                    parser.ids++;
                    RESULT = newVal;

                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // PREFIXREGEX ::= stringVal 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$Syntactical$stack.peek()).value;
		  
                    String contenido = (String)o;
                    //String [] concat=contenido.split("\"");//eliminando las comillas de la cadena para que no de error al generar el png
                    System.out.println("nuevo string"); 
                    AST newVal = new AST(parser.ids, contenido, null, null );
                    parser.ids++;
                    RESULT = newVal;

                
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("PREFIXREGEX",8, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EVALUATION ::= id colon stringVal semicolon 
            {
              Object RESULT =null;
		 System.out.println("Nuevo lexema a evaluar"); 
              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("EVALUATION",3, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-3)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // LISTVAL ::= id comma LISTVAL 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("LISTVAL",7, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // LISTVAL ::= id 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("LISTVAL",7, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ASCIIS ::= asciiChar comma ASCIIS 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("ASCIIS",9, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.elementAt(CUP$Syntactical$top-2)), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ASCIIS ::= asciiChar 
            {
              Object RESULT =null;

              CUP$Syntactical$result = parser.getSymbolFactory().newSymbol("ASCIIS",9, ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), ((java_cup.runtime.Symbol)CUP$Syntactical$stack.peek()), RESULT);
            }
          return CUP$Syntactical$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Syntactical$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Syntactical$do_action(
    int                        CUP$Syntactical$act_num,
    java_cup.runtime.lr_parser CUP$Syntactical$parser,
    java.util.Stack            CUP$Syntactical$stack,
    int                        CUP$Syntactical$top)
    throws java.lang.Exception
    {
              return CUP$Syntactical$do_action_part00000000(
                               CUP$Syntactical$act_num,
                               CUP$Syntactical$parser,
                               CUP$Syntactical$stack,
                               CUP$Syntactical$top);
    }
}

}
